' Aufgabe_02_03_03

' Zur Beschreibung eines Systems erhalten Sie die folgenden Informationen:

' Ein User kann beim Nutzen eines Lern-Programmes neue Vokabeln eingeben, 
' oder Vokabeln trainieren. 

' Falls eine eingegebene Vokabel bereits vorhanden ist, wird vom Programm 
' eine Fehlermeldung ausgegeben, ansonsten wird die neue Vokabel vom 
' Programm abgespeichert.

' Falls der User sich dafür entscheidet, Vokabeln zu trainieren, so werden 
' vom Programm stets Vokabeln angezeigt. Ebenfalls wird der User stets 
' Antworten eingeben können. Ferner wird das Programm nach jeder Eingabe 
' stets die aktuelle Erfolgsquote ausgeben. 

' Hingegen wird die korrekte Antwort vom Programm nur in jenen Fällen 
' angezeigt, in denen die zuvor vom User eingegebene Antwort fehlerhaft 
' war.

@startuml

title Lern-Programm

left to right direction
actor user as "User" #BlueViolet
rectangle lern_programm as "Lern-Programm" {
	(Neue Vokabel eingeben)
	(Trainiere Vokabeln)


user --> (Neue Vokabel eingeben) : neue Vokabel eingeben
user --> (Trainiere Vokabeln) : Vokabeln trainieren
(Neue Vokabel eingeben) --> (Fehlermeldung ausgeben) : Vokabel bereits vorhanden
(Trainiere Vokabeln) --> (Vokabeln anzeigen) : Vokabeln anzeigen
(Trainiere Vokabeln) --> (Antwort eingeben) : Antwort eingeben
(Trainiere Vokabeln) --> (Erfolgsquote ausgeben) : Erfolgsquote ausgeben
(Trainiere Vokabeln) --> (Korrekte Antwort anzeigen) : Korrekte Antwort anzeigen
	
}



@enduml