' AKTEURE DEFINIEREN (ОПРЕДЕЛЕНИЕ АКТЁРОВ)
@startuml

title Проба пера!

left to right direction 

actor gast as "Gust" #BlueViolet 
actor kunde as "Kunde" #Green 

' note left of kunde : muss eingeloggt sein


' Элемент "database" для хранения данных:
' database KundenstammDB as "DB" #LightBlue 
' entity vasia as "Vasiliy (Server)" #LightGreen
rectangle warenkorbSystem as "Website / Server" {

usecase kunde_anmeldung as "kunde anmeldung" #Green 
usecase goods_serch as "goods_serch" #Orange
usecase chouse_good as "Chouse" #LightGreen 
}
' Gast --|> Kunde
' ' RegistrierterKunde --|> Kunde

gast -> kunde_anmeldung #Red
kunde_anmeldung --> kunde 
gast <|-> kunde #Blue :wird as 
kunde <--> goods_serch #blue
kunde --> chouse_good 



@enduml